
/* 
    dette er en testfil for funfacts. funfacts her er ikke faktasjekket.

    format: [[kg CO2, tekst1],[kg CO2, tekst2]]
*/

export function Funfacts () {
    const funfactArray = 
        [
        [1, "Mengden CO2 du slipper ut ved å puste i ett døgn"],
        //[10, "Denne mengden kan 10 roser absorbere"],
        [30, "Tilsvarer en biltur mellom Hamar og Oslo"],
        [60, "Mengden CO2 absorbert av 200 epler"],
        [100, "Mengden CO2 sluppet ut av en vedsekk"],
        [180, "CO2 i oboy"],
        [900, "Den lagrede CO2en i et fullvoksent grantre med stamme, greiner og røtter"]
        ]
    return (funfactArray)
}


export function ManyFunfactsDict() {
    const funDict =
    {
        0   :   [   "	bare ingenting slipper ut ingenting	", " hei", "på "	]	,
        1	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        2	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        3	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        4	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        5	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        6	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        7	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        8	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        9	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        10	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        11	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        12	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        13	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        14	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        15	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        16	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        17	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        18	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        19	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        20	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        21	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        22	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        23	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        24	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        25	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        26	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        27	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        28	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        29	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        30	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        31	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        32	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        33	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        34	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        35	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        36	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        37	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        38	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        39	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        40	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        41	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        42	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        43	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        44	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        45	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        46	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        47	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        48	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        49	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        50	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        51	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        52	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        53	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        54	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        55	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        56	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        57	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        58	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        59	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        60	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        61	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        62	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        63	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        64	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        65	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        66	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        67	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        68	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        69	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        70	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        71	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        72	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        73	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        74	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        75	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        76	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        77	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        78	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        79	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        80	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        81	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        82	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        83	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        84	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        85	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        86	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        87	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        88	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        89	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        90	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        91	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        92	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        93	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        94	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        95	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        96	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        97	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        98	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        99	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        100	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        101	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        102	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        103	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        104	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        105	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        106	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        107	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        108	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        109	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        110	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        111	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        112	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        113	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        114	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        115	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        116	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        117	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        118	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        119	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        120	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        121	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        122	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        123	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        124	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        125	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        126	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        127	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        128	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        129	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        130	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        131	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        132	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        133	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        134	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        135	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        136	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        137	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        138	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        139	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        140	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        141	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        142	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        143	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        144	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        145	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        146	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        147	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        148	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        149	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        150	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        151	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        152	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        153	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        154	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        155	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        156	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        157	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        158	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        159	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        160	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        161	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        162	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        163	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        164	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        165	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        166	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        167	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        168	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        169	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        170	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        171	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        172	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        173	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        174	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        175	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        176	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        177	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        178	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        179	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        180	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        181	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        182	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        183	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        184	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        185	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        186	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        187	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        188	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        189	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        190	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        191	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        192	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        193	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        194	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        195	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        196	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        197	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        198	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        199	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        200	:	[	"	tekst 1	"	,	"	tekst2	"	,	"	tekst 3	"	,	]	,
        }
    return funDict
}